### ISSUE TITLE
conceal unit

### ISSUE THREAD

**Issue by mathiasverraes** [zjhmale/intellij-haskell-conceal#4]
If I'm not mistaken, the symbol for unit () is ∅ (U+2205)
eg main :: IO ∅

**Comment by mathiasverraes** [comment]
hm I just realised that [] == ∅. Not sure what () is then :-S

**Comment by swr1bm86** [comment]
@mathiasverraes for now there is no symbol stand for `()`, empty list `[]` conceal to `Ø`, `mzero` and `mempty` conceal to `∅`. i will support unit conceal to `∅` anyway.
