### ISSUE TITLE
conceal ++ (concat)

### ISSUE THREAD

**Issue by mathiasverraes** [zjhmale/intellij-haskell-conceal#5]
⧺
DOUBLE PLUS
Unicode: U+29FA, UTF-8: E2 A7 BA

**Comment by swr1bm86** [comment]
@mathiasverraes got it, i will support it soon :)

**Comment by swr1bm86** [comment]
@mathiasverraes we now get `++` and `()` concealed, and new version is also released, time to update the plugin, Cheers! 🎉

**Comment by mathiasverraes** [comment]
awesome, keep up the great work :)
